version: '3.8'

services:
  db_rtrw_service:
    image: postgres
    container_name: db_rtrw2      
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - ./database/rtrw.sql:/docker-entrypoint-initdb.d/rtrw.sql
    restart: unless-stopped
